# Generated by Django 2.2 on 2021-01-25 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jietu', '0002_doamin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doamin',
            name='user',
        ),
        migrations.AddField(
            model_name='doamin',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='域名归属'),
        ),
    ]
